### ISSUE TITLE
有无办法绕过“配置企业可信IP前，请先 设置可信域名 或 设置接收消息服务器URL”

### ISSUE THREAD

**Issue by WatsonCao** [lyc8503/WechatPush#1]
现在应用如果设置可信IP的话，要先设置可信域名 或 设置接收消息服务器URL
![image](https://user-images.githubusercontent.com/25975419/192935323-a6e3a33b-122f-479b-8e0c-64f50e8a4454.png)

**Comment by lyc8503** [comment]
不好意思我不太清楚. 为什么需要设置企业可信 IP 呢?

**Comment by WatsonCao** [comment]
不知道是不是我特有的问题，不设置 可信IP，wecomchan或者说 企业微信官方 会返回 错误报文，提示需要设置IP，不然不允许发送
{'errcode': 60020, 'errmsg': 'not allow to access from your ip, hint: [1665631550347282440343881], from ip: ********, more info at https://open.work.weixin.qq.com/devtool/query?e=60020'}

可以参考
https://github.com/easychen/wecomchan/issues/72

**Comment by lyc8503** [comment]
我这里之前操作的时候没有遇到这个问题, 那你看看能否按照它的指引添加接收消息服务器URL或者可信域名呢?

**Comment by WatsonCao** [comment]
这个只有 公司才有，因为需要用 公司主体备案，所以相当于个人的话，或者小组就没法用了

**Comment by lyc8503** [comment]
我是用个人账号配置的, 没有遇到这个问题. 不知道是个例还是规则更新了, 如果以后有类似问题我会再更新说明.
