### ISSUE TITLE
无法推送

### ISSUE THREAD

**Issue by Linkfufu** [lyc8503/WechatPush#2]
您好，已经按照readme的说明去配置了，然后调用以下代码后，无法在微信上收到消息：

push = WechatPush(corp_id, secret, agent_id)
push.send_text('Hello!\n文本支持换行\n<a href="https://github.com">文本支持超链接</a>')

是否需要“配置企业可信IP”？

**Comment by lyc8503** [comment]
有可能是的, 已经更新了 README 设置可信 IP 相关的说明, 你设置一下试试.

`send_text` 方法的返回值应该包含了相关的错误信息, 可以打印出来看看

**Comment by Linkfufu** [comment]
> 有可能是的, 已经更新了 README 设置可信 IP 相关的说明, 你设置一下试试.
> 
> `send_text` 方法的返回值应该包含了相关的错误信息, 可以打印出来看看

您好，send_text的返回值是 'errmsg': 'not allow to access from your ip xxx'。

我没有公网IP，没有服务器，只有本地电脑。请问该如何配置可信IP呢？

**Comment by lyc8503** [comment]
可以使用在线网站查自己的 ip 后进行设置，对应的公网 ip 会不会变动取决于运营商，光猫不重新拨号一般 ip 不变
